// Expansion of Flux shorthand attributes into HTMX attributes.
//
// Precedence (spec §2, §7): raw `hx-*` always wins. If an element already declares the
// target HTMX attribute and it was NOT generated by Flux, Flux leaves it untouched.

import { log } from './logger.js';
import {
  setGeneratedAttribute,
  removeGeneratedAttribute,
  hasGeneratedAttribute,
} from './generated-attributes.js';
import { applyRecipe, attributeForKey, hasExplicitAttribute } from './recipes.js';

// Verbs make an element actionable (matched by HTMX's `[hx-get],[hx-post],...` selector).
const VERBS = ['get', 'post', 'put', 'patch', 'delete'] as const;

// Generic option aliases were removed in 2.0: fx-target, fx-swap, fx-trigger, fx-select,
// fx-sync, fx-include, fx-vals, fx-headers, fx-confirm, fx-boost, fx-preload, and
// fx-preserve were 1:1 renames of the hx-* attributes with no added behaviour. Use the
// raw hx-* attributes next to an fx-* verb. Presets keep reading their own option
// attributes (fx-target, fx-swap, fx-confirm, ...) directly via ctx().
//
// fx-indicator stays a generic alias: presets and raw verbs both consume it everywhere.
const OPTIONS = ['indicator'] as const;

// One selector matching any Flux shorthand attribute, used for subtree discovery.
const FLUX_SELECTOR = [
  ...VERBS,
  ...OPTIONS,
  'morph',
  'history',
  'recipe',
  'scope',
  'confirm-dialog',
]
  .map((n) => `[fx-${n}]`)
  .join(',');

/** Returns true if `element` carries any Flux shorthand verb or option attribute. */
export function hasFluxAttributes(element: Element): boolean {
  return element instanceof Element && element.matches(FLUX_SELECTOR);
}

/** CSS selector matching any element carrying a Flux shorthand attribute. */
export function fluxSelector(): string {
  return FLUX_SELECTOR;
}

/**
 * Expands Flux shorthand on `element` into HTMX attributes.
 *
 * Raw `hx-*` wins: an existing HTMX attribute is never overwritten unless owned by Flux.
 * Returns the number of attributes written this call.
 */
export function expandElement(element: Element): number {
  if (!(element instanceof Element)) return 0;

  applyRecipeAndScope(element);

  let written = 0;
  for (const verb of VERBS) written += syncShorthand(element, verb);
  for (const option of OPTIONS) written += syncShorthand(element, option);

  if (element.hasAttribute('fx-confirm-dialog')) {
    if (setGeneratedAttribute(element, 'hx-confirm', 'flux-confirm-dialog')) {
      element.setAttribute('data-flux-gen-confirm-dialog', '1');
      written++;
    }
  } else if (element.hasAttribute('data-flux-gen-confirm-dialog')) {
    removeGeneratedAttribute(element, 'hx-confirm');
    element.removeAttribute('data-flux-gen-confirm-dialog');
    written += syncShorthand(element, 'confirm');
  }

  // fx-prefetch is a Flux preset, not an HTMX shorthand.
  if (element.hasAttribute('data-flux-gen-shorthand-prefetch')) {
    removeGeneratedAttribute(element, 'hx-prefetch');
    element.removeAttribute('data-flux-gen-shorthand-prefetch');
  }

  if (element.hasAttribute('fx-morph')) {
    const rawVal = element.getAttribute('fx-morph')?.trim().toLowerCase() ?? '';
    const validModes: Record<string, string> = {
      '': 'innerMorph',
      inner: 'innerMorph',
      outer: 'outerMorph',
      sync: 'outerSync',
    };
    if (rawVal && !(rawVal in validModes)) {
      log.warn(`invalid fx-morph value "${rawVal}"; falling back to "innerMorph"`);
    }
    const swapMode = validModes[rawVal] ?? 'innerMorph';
    if (setGeneratedAttribute(element, 'hx-swap', swapMode)) {
      element.setAttribute('data-flux-gen-shorthand-morph', '1');
      written++;
    }
  } else if (element.hasAttribute('data-flux-gen-shorthand-morph')) {
    removeGeneratedAttribute(element, 'hx-swap');
    element.removeAttribute('data-flux-gen-shorthand-morph');
  }

  if (element.hasAttribute('fx-history')) {
    const val = element.getAttribute('fx-history') || 'true';
    if (setGeneratedAttribute(element, 'hx-push-url', val)) {
      element.setAttribute('data-flux-gen-shorthand-history', '1');
      written++;
    }
  } else if (element.hasAttribute('data-flux-gen-shorthand-history')) {
    removeGeneratedAttribute(element, 'hx-push-url');
    element.removeAttribute('data-flux-gen-shorthand-history');
  }

  return written;
}

/** Syncs `fx-name` shorthand to `hx-name`. Removes generated `hx-name` if `fx-name` shorthand was removed. */
function syncShorthand(element: Element, name: string): 0 | 1 {
  const fxAttr = `fx-${name}`;
  const hxAttr = `hx-${name}`;
  const marker = `data-flux-gen-shorthand-${name}`;

  const fxValue = element.getAttribute(fxAttr);
  if (fxValue === null) {
    if (element.hasAttribute(marker)) {
      removeGeneratedAttribute(element, hxAttr);
      element.removeAttribute(marker);
    }
    return 0;
  }

  const written = setGeneratedAttribute(element, hxAttr, fxValue);
  if (written || hasGeneratedAttribute(element, hxAttr)) {
    element.setAttribute(marker, '1');
  }
  return written ? 1 : 0;
}

const recipeOwnedAttributes = new WeakMap<Element, Map<string, string>>();
const scopeOwnedAttributes = new WeakMap<Element, Map<string, string>>();
// WeakRef registry — strong Set references leaked detached elements (sugar remove,
// fx-remove). Dead refs are dropped lazily during iteration.
const recipeAndScopeRefs = new Set<WeakRef<Element>>();

function trackRecipeScopeElement(element: Element): void {
  recipeAndScopeRefs.add(new WeakRef(element));
}

function trackedRecipeScopeElements(): Element[] {
  const live: Element[] = [];
  for (const ref of recipeAndScopeRefs) {
    const el = ref.deref();
    if (el) live.push(el);
    else recipeAndScopeRefs.delete(ref);
  }
  return live;
}

function untrackRecipeScopeElement(element: Element): void {
  for (const ref of recipeAndScopeRefs) {
    if (ref.deref() === element) {
      recipeAndScopeRefs.delete(ref);
      return;
    }
  }
}

export function applyRecipeAndScope(element: Element): void {
  clearOwnedAttributes(element, recipeOwnedAttributes, 'data-flux-recipe-owned');
  clearOwnedAttributes(element, scopeOwnedAttributes, 'data-flux-scope-owned');
  untrackRecipeScopeElement(element);

  // Apply Recipe
  if (element.hasAttribute('fx-recipe')) {
    const writtenKeys = new Map<string, string>();
    applyRecipe(element, element.getAttribute('fx-recipe') || '', writtenKeys);
    if (writtenKeys.size > 0) {
      recipeOwnedAttributes.set(element, writtenKeys);
      trackRecipeScopeElement(element);
      element.setAttribute('data-flux-recipe-owned', '1');
    }
  }

  // Apply Scope(s) Bottom-Up
  const scopes = getScopesBottomUp(element);
  if (scopes.length > 0) {
    const writtenKeys = new Map<string, string>();
    for (const scope of scopes) {
      applyScope(element, scope, writtenKeys);
    }
    if (writtenKeys.size > 0) {
      scopeOwnedAttributes.set(element, writtenKeys);
      trackRecipeScopeElement(element);
      element.setAttribute('data-flux-scope-owned', '1');
    }
  }
}

export function removeRecipeAndScopeAttributes(root?: Element): void {
  for (const element of trackedRecipeScopeElements()) {
    if (root && element !== root && !root.contains(element)) continue;
    clearOwnedAttributes(element, recipeOwnedAttributes, 'data-flux-recipe-owned');
    clearOwnedAttributes(element, scopeOwnedAttributes, 'data-flux-scope-owned');
    untrackRecipeScopeElement(element);
  }
}

function clearOwnedAttributes(
  element: Element,
  registry: WeakMap<Element, Map<string, string>>,
  marker: string,
): void {
  const owned = registry.get(element);
  if (owned) {
    for (const [name, value] of owned) {
      if (element.getAttribute(name) === value) element.removeAttribute(name);
    }
    registry.delete(element);
  }
  element.removeAttribute(marker);
}

function getScopesBottomUp(element: Element): Element[] {
  const scopes: Element[] = [];
  let current: Element | null = element.parentElement;
  while (current) {
    if (current.hasAttribute('fx-scope')) {
      scopes.push(current);
    }
    current = current.parentElement;
  }
  return scopes;
}

/** Inherits defaults from the nearest fx-scope if not explicitly set on the element */
function applyScope(element: Element, scope: Element, writtenKeys: Map<string, string>): void {
  for (const attr of Array.from(scope.attributes)) {
    if (attr.name.startsWith('fx-default-')) {
      const key = attr.name.replace('fx-default-', '');
      if (!hasExplicitAttribute(element, key)) {
        const attrName = attributeForKey(key);
        element.setAttribute(attrName, attr.value);
        writtenKeys.set(attrName, attr.value);
      }
    }
  }
}
