// Generates src/core/version.ts from package.json so FLUX_VERSION can never drift
// from the published version. Runs on prebuild and pretest.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

const content = `// GENERATED by scripts/generate-version.mjs — do not edit by hand.
// Source of truth: package.json "version".
export const FLUX_VERSION = '${pkg.version}';
`;

writeFileSync(join(root, 'src', 'core', 'version.ts'), content);
console.log(`[generate-version] FLUX_VERSION = ${pkg.version}`);
